In [1]:
import numpy as np

In [6]:
# 3D array

arr3D = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]]) #two depths are present here 0 & 1
print(arr3D, arr3D.shape)

# indexing
print(arr3D[0, 1, 1]) #[depth, row, colm]

# slicing
print(arr3D[:, 0, :]) #first row from both layers
print(arr3D[:, :, 0]) #first coloumn from both layers

# manipulate array
(arr3D[:, 0, :]) = 99 #us specific index par ki value replace hogi 99 se
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]
