In [1]:
import numpy as np


In [2]:
# properties
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr.shape) #dimentions
print(arr.size) #total elements
print(arr.dtype) #datatype
print(arr.ndim) #no. of dimentions value


# typecasting
float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64
