In [9]:
import numpy as np

In [13]:
# create - form list
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.shape, arr.dtype)

arr2 = np.array([1, 2, 3, 4, 5, "prime"])
print(arr2, type(arr2), arr2.shape, arr2.dtype)
# the array is 1D thats why 1D array me humesha no. of elements type hote hai

# 2D array
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr2D, type(arr2D), arr2D.shape, arr2D.dtype)

# yahape dimention(shape) (4, 3) hai means matrix (4*3) ka hai 
# hum yaha har row me 3 hi elements le sakate hai 3 se jyada nahi kyuki numpy array homogeneous hai coloumn ki

[1 2 3 4 5] <class 'numpy.ndarray'> (5,) int64
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> (6,) <U21
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] <class 'numpy.ndarray'> (4, 3) int64
