In [1]:
import numpy as np

In [2]:
# indexing - printing the element on specific index

# 1D array
arr = np.array([1, 2, 3, 4, 5])
print(arr[0]) #0th index par ka element print hoga
print(arr[3]) #3rd index par ka element print hoga

1
4


In [7]:
# 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[0] [1])

2


In [9]:
# Fancy Indexing- if we wanna print the multiple indexes in same array
arr = np.array([1, 2, 3, 4, 5])
idx = [0, 1, 3]
print(arr[idx])

[1 2 4]


In [12]:
# Boolean Indexing- true & false condition
arr = np.array([1, 2, 3, 4, 5])
print(arr[arr > 2]) #if condition true hai to arr me jitane bhi greater than 2 ele print hoge
print(arr[arr % 2 == 0]) #if condition true hai to even no. print hoge
print(arr[arr % 2 != 0]) #odd no.s

[3 4 5]
[2 4]


In [13]:
# Slcling - [start, end , step]
arr = np.array([1, 2, 3, 4, 5])
print(arr[1:4]) #[start-1, end-goes to 4 but not include its ele , step-0]
print(arr[1:]) #[start-1, end-default/last , step-0]
print(arr[:4]) #[start-default/0th, end-4(not include) , step-0]
print(arr[::2]) #[start-default/0th, end-default/4th , step-2]

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 3 5]
