In [2]:
import numpy as np

In [11]:
# create
arr1 = np.zeros((2, 3), dtype="int64") #prefill- pehelese array me elements fill kar rahe hai
print(arr1, arr1.shape)
# yaha humne prefill zero ko kiya hai isiliye zero print hoge & 2*3 ka matrix banega

arr2 = np.ones((2, 3)) # humne yahape int4 datatype specify nahi kiay to by default float aayega
print(arr2, arr2.shape)
# prefil with 1

arr3 = np.full((2, 3), 100) 
print(arr3, arr3.shape)
# prefill with value

arr4 = np.eye(3) # here 3 means humara matrix 3*3 ka hoga. Identity matrix is always square matrix thats why we pass 3 only
print(arr4, arr4.shape)
# prefill with identity matrix

arr5 = np.arange(0, 11, 2) #range elements. arrary start from 0 to 10(11 hai to 10 tak hi badhega) & 2 steps skip karega, just like if we wanna print only odd or even no.s
print(arr5, arr5.shape)

arr6 = np.linspace(1, 100, 3) #evenly spaced arays. array 1 se start hofi 100 par end hogi and no. of elements in array sirf 3 hoge jo ki evenly spaced hoge  matlab 100 ke 3 parts me equally divide hoge
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]] (2, 3)
[[100 100 100]
 [100 100 100]] (2, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.   50.5 100. ] (3,)
