In [1]:
import numpy as np

In [2]:
# Aggregation functions

arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr)) #prints min index in the arr
print(np.argmax(arr)) #prints max index in the arr

print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))


15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [4]:
# power function
arr = np.array([1, 2, 3, 4, 5])

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr, 3)) #elements to the power something

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [7]:
# log function

arr = np.array([1, 2, 3, 4, 5])

print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))

print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [8]:
# rounding off function 

print(np.round(3.14)) #roun off
print(np.ceil(3.14)) #round up
print(np.floor(3.14)) #round down
print(np.trunc(3.14)) #truncate the value after decimal

3.0
4.0
3.0
3.0


In [12]:
#extra functions
arr = np.array([1, -2, 3, 4, 5, -5, 2])

print(np.unique(arr)) #it will print all unique values in the arr not repeated
print(np.sort(arr))
print(np.abs(arr)) #it makes all the values positive

[-5 -2  1  2  3  4  5]
[-5 -2  1  2  3  4  5]
[1 2 3 4 5 5 2]
