In [1]:
import numpy as np

In [4]:
# vectorization- not using theloops and saving the space and time

arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1, 2, 3, 4, 5])

print(arr ** 2)
print(arr + 2)
print(arr + arr2)

[ 1  4  9 16 25]
[3 4 5 6 7]
[ 2  4  6  8 10]


In [7]:
# broadcasting- scaling our array without using extra memory

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])

print(arr1. shape)
print(arr2.shape)

print(arr1 + arr2)

# hum 1st array agar chota ho to hi use 2nd array ke sath add kar sakate hai agar humara arr2 agar arr1 hota to error aata

(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]
